
export const REGION_MAP: Record<string, string> = {
  'ARICA Y PARINACOTA': 'Región de Arica y Parinacota',
  'TARAPACA': 'Región de Tarapacá',
  'ANTOFAGASTA': 'Región de Antofagasta',
  'ATACAMA': 'Región de Atacama',
  'COQUIMBO': 'Región de Coquimbo',
  'VALPARAISO': 'Región de Valparaíso',
  'METROPOLITANA': 'Región Metropolitana de Santiago',
  'RM': 'Región Metropolitana de Santiago',
  'REGION METROPOLITANA': 'Región Metropolitana de Santiago',
  'O\'HIGGINS': 'Región del Libertador General Bernardo O\'Higgins',
  'OHIGGINS': 'Región del Libertador General Bernardo O\'Higgins',
  'MAULE': 'Región del Maule',
  'ÑUBLE': 'Región de Ñuble',
  'NUBLE': 'Región de Ñuble',
  'BIOBIO': 'Región del Biobío',
  'BIO-BIO': 'Región del Biobío',
  'ARAUCANIA': 'Región de La Araucanía',
  'LOS RIOS': 'Región de Los Ríos',
  'LOS LAGOS': 'Región de Los Lagos',
  'AYSEN': 'Región de Aysén del General Carlos Ibáñez del Campo',
  'MAGALLANES': 'Región de Magallanes y de la Antártica Chilena',
};
